# Generated by Django 5.0.3 on 2024-03-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='No bio yet'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('BULKING', 'Bulking'), ('CUTTING', 'Cutting'), ('MAINTAINING', 'Maintaining'), ('NOT_GIVEN', 'Not Given')], default='NOT_GIVEN', max_length=11),
        ),
    ]
